export const PRODUCTS = [
  {
    id: 0,
    name: 'Specialty Latté',
    image: '/assets/products/latte--specialty.jpg',
    description: '',
    price: '$3.00',
  },
  {
    id: 1,
    name: 'Maple Latté',
    image: '/assets/products/latte--maple.jpg',
    description: '',
    price: '$3.25',
  },
  {
    id: 2,
    name: 'Latté',
    image: '/assets/products/latte.jpg',
    description: '',
    price: '$2.75',
  },
  {
    id: 3,
    name: 'Honey Cinnamon Latté',
    image: '/assets/products/latte--honey-cinnamon.jpg',
    description: '',
    price: '$3.00',
  },
  {
    id: 4,
    name: 'Cortado',
    image: '/assets/products/cortado.jpg',
    description: 'Double shot expresso with steamed milk (1-1 ratio).',
    price: '$3.00',
  },

  {
    id: 5,
    name: 'Coffee - v60 Cone Drip',
    image: '/assets/products/v60-cone-drip.jpg',
    description: 'Cone dripped black coffee.',
    price: '$2.00-$2.50',
  },
  {
    id: 6,
    name: 'Cappuccino - 7oz.',
    image: '/assets/products/cappuccino.jpg',
    description:
      'Classic 7oz. cappuccino with double shot of espresso and frothed milk.',
    price: '$3.25',
  },

  {
    id: 7,
    name: 'Matcha Latté',
    image: '/assets/products/latte--matcha.jpg',
    description:
      'Our matcha latté is made with Japanese matcha, frothed milk, and choice of flavor.',
    price: '$3.00-$4.00',
  },
  {
    id: 8,
    name: 'Iced Matcha Latté',
    image: '/assets/products/latte--iced-matcha.jpg',
    description:
      'Our Iced Match Latté is a refreshing combination of milk, Japanese matcha, and a small amount of flavoring if desired.',
    price: '$3.00-$4.00',
  },
  {
    id: 9,
    name: 'Chai Latté',
    image: '/assets/products/latte--chai.jpg',
    description:
      'Made with our delicious in house spiced chai combined with frothed milk.',
    price: '$3.00',
  },
  {
    id: 10,
    name: 'Smoothie - Traditional',
    image: '/assets/products/smoothie--traditional.jpg',
    description:
      'Orange juice based smoothies with yogurt, bananas and selected fruit.',
    price: '$3.50-$4.00',
  },
  {
    id: 11,
    name: 'Smoothie - Creamy',
    image: '/assets/products/smoothie--creamy.jpg',
    description:
      'Milk based smoothies with yogurt, bananas and selected fruit.',
    price: '$3.50-$4.00',
  },
  {
    id: 12,
    name: 'Smoothie - Signature',
    image: '/assets/products/smoothie--signature.jpg',
    description:
      "Choose from 'Kale Sunrise', 'Peanut Butter Mango', 'Tropical', 'Banana Split' and 'Coconut Paradise'.",
    price: '$4.00-$4.25',
  },
  {
    id: 13,
    name: 'Hot Chocolate',
    image: '/assets/products/hot-chocolate.jpg',
    description: '',
    price: '$2.25',
  },
  {
    id: 14,
    name: 'Steeped Tea',
    image: '/assets/products/steeped-tea.jpg',
    description: '',
    price: '$1.75',
  },
  {
    id: 15,
    name: 'Iced Tea',
    image: '/assets/products/iced-tea.jpg',
    description: '',
    price: '$1.75',
  },
  {
    id: 16,
    name: 'Italian Soda',
    image: '/assets/products/italian-soda.jpg',
    description: '',
    price: '$2.00',
  },
  {
    id: 17,
    name: 'Hot Cider',
    image: '/assets/products/hot-cider.jpg',
    description: 'Hot caramel cider - variations on the seasonal classic.',
    price: '$3.00',
  },
  {
    id: 18,
    name: 'Winter Wheat Bread - Loaf',
    image: '/assets/products/winter-wheat-loaf.jpg',
    description: 'Please allow 2 business days for pick-ups.',
    price: '$5',
  },
  {
    id: 19,
    name: 'Scones',
    image: '/assets/products/scones.jpg',
    description: 'Our scones are all made from scratch.',
    price: '$2.25-2.50',
  },

  {
    id: 20,
    name: 'Cookies',
    image: '/assets/products/cookies.jpg',
    description: '',
    price: '$1.00',
  },
  {
    id: 21,
    name: 'Breakfast Sandwhich',
    image: '/assets/products/breakfast--sandwhich.jpg',
    description: '',
    price: '$4.00-$4.50',
  },
  {
    id: 22,
    name: 'Bagels & Scones',
    image: '/assets/products/breakfast--bagel-scone.jpg',
    description: '',
    price: '$2.00-$3.50',
  },
  {
    id: 23,
    name: 'Steel Cut Oats',
    image: '/assets/products/breakfast--steel-cut-oats.jpg',
    description: '',
    price: '$2.00',
  },
  {
    id: 24,
    name: 'Granola',
    image: '/assets/products/breakfast--granola.jpg',
    description: '',
    price: '$2.25',
  },
  {
    id: 25,
    name: 'Toast',
    image: '/assets/products/breakfast--toast.jpg',
    description: '',
    price: '$0.75',
  },
  {
    id: 26,
    name: 'Sandwhiches',
    image: '/assets/products/lunch--sandwich.jpg',
    description: '',
    price: '$3.00-$4.75',
  },
  {
    id: 27,
    name: 'Soup',
    image: '/assets/products/lunch--soup.jpg',
    description: '',
    price: '$2.25',
  },
  {
    id: 28,
    name: 'Retail Coffee Beans',
    image: '/assets/products/coffee-beans.jpg',
    description: '',
    price: '$0.53-$8.25/oz.',
  },
];
